### ISSUE TITLE
game freeze if click on non empty space on grid

### ISSUE THREAD

**Issue by josmardias** [francismozart/tic-tac-toe#7]
_what is happening:_
If I choose a space on grid  that is not empty, the timer and the game stops forever.

![image](https://user-images.githubusercontent.com/413430/42471625-d2a528ee-8394-11e8-8291-aa3a7910accb.png)

_what should happen:_
Nothing, the game should continue like if I didn't choose any space.

**Comment by francismozart** [comment]
Corrected [by this commit](https://github.com/francismozart/tic-tac-toe/commit/f723ddf3cfa3065d061b7e673b969feb79809eaa).
